/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xd_dl_job_ParkNative */

#ifndef _Included_xd_dl_job_ParkNative
#define _Included_xd_dl_job_ParkNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xd_dl_job_ParkNative
 * Method:    initialized
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xd_dl_job_ParkNative_initialized
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    unitialized
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xd_dl_job_ParkNative_unitialized
  (JNIEnv *, jclass);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    getParkedCarInfo
 * Signature: (ILjava/lang/String;IIILjava/lang/String;Ljava/lang/String;)Lxd/dl/job/ParkedCarInfo;
 */
JNIEXPORT jobject JNICALL Java_xd_dl_job_ParkNative_getParkedCarInfo
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jstring, jstring);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    payParkCarFee
 * Signature: (ILjava/lang/String;Ljava/lang/String;FLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_xd_dl_job_ParkNative_payParkCarFee
  (JNIEnv *, jclass, jint, jstring, jstring, jfloat, jstring, jstring, jint);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    getLeftParkInfo
 * Signature: ()[Lxd/dl/job/LeftParkInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_xd_dl_job_ParkNative_getLeftParkInfo
  (JNIEnv *, jclass);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    getCarportInfo
 * Signature: (Ljava/lang/String;)[Lxd/dl/job/ViewCarportRoomInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_xd_dl_job_ParkNative_getCarportInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    payCarportRent
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;IFZ)I
 */
JNIEXPORT jint JNICALL Java_xd_dl_job_ParkNative_payCarportRent
  (JNIEnv *, jclass, jstring, jstring, jstring, jobjectArray, jstring, jint, jfloat, jboolean);

#ifdef __cplusplus
}
#endif
#endif
